<a href="https://colab.research.google.com/github/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/blob/main/Notebooks/mvpcriminal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.gov.br/mj/pt-br/assuntos/sua-seguranca/seguranca-publica/estatistica/dados-nacionais-1/base-de-dados-e-notas-metodologicas-dos-gestores-estaduais-sinesp-vde-2022-e-2023

In [3]:
#importação das bibliotecas necessárias ao desenvolvimento do MVP
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#importação das bases de dados

url_2020 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2020.csv"
url_2021 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2021.csv"
url_2022 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2022.csv"
url_2023 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2023.csv"
url_2024 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2024.csv"
url_2025 = "https://raw.githubusercontent.com/Marcelo-Silvestre/MVP_Machine_Learning_Analytics_PUCRIO_40530010056_20260_01/main/arquivos/BancoVDE_2025.csv"

df_2020 = pd.read_csv(url_2020,sep=";")
df_2021 = pd.read_csv(url_2021,sep=";")
df_2022 = pd.read_csv(url_2022,sep=";")
df_2023 = pd.read_csv(url_2023,sep=";")
df_2024 = pd.read_csv(url_2024,sep=";")
df_2025 = pd.read_csv(url_2025,sep=";")

/tmp/ipykernel_15782/3800459640.py:15: DtypeWarning: Columns (4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025 = pd.read_csv(url_2025,sep=";")

In [17]:
df_2020.head(5)

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,1/1/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,1/2/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,1/3/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,1/4/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,1/5/2020,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [18]:
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764604 entries, 0 to 764603
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   uf               764604 non-null  object
 1   municipio        764604 non-null  object
 2   evento           764604 non-null  object
 3   data_referencia  764604 non-null  object
 4   agente           5832 non-null    object
 5   arma             5832 non-null    object
 6   faixa_etaria     1944 non-null    object
 7   feminino         660106 non-null  float64
 8   masculino        660568 non-null  float64
 9   nao_informado    659860 non-null  float64
 10  total_vitima     685068 non-null  float64
 11  total            75655 non-null   float64
 12  total_peso       1176 non-null    float64
 13  abrangencia      764604 non-null  object
dtypes: float64(6), object(8)
memory usage: 81.7+ MB

In [10]:
df_2021.head()

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,1/1/2021,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,1/2/2021,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,1/3/2021,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,1/4/2021,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,1/5/2021,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [19]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764604 entries, 0 to 764603
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   uf               764604 non-null  object
 1   municipio        764604 non-null  object
 2   evento           764604 non-null  object
 3   data_referencia  764604 non-null  object
 4   agente           5832 non-null    object
 5   arma             5832 non-null    object
 6   faixa_etaria     1944 non-null    object
 7   feminino         671741 non-null  float64
 8   masculino        672385 non-null  float64
 9   nao_informado    672366 non-null  float64
 10  total_vitima     685068 non-null  float64
 11  total            76692 non-null   float64
 12  total_peso       1176 non-null    float64
 13  abrangencia      764604 non-null  object
dtypes: float64(6), object(8)
memory usage: 81.7+ MB

In [11]:
df_2022.head()

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,1/1/2022,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,1/2/2022,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,1/3/2022,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,1/4/2022,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,1/5/2022,NaN,NaN,NaN,1.0,0.0,0.0,1.0,NaN,NaN,Estadual

In [20]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764508 entries, 0 to 764507
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   uf               764508 non-null  object
 1   municipio        764508 non-null  object
 2   evento           764508 non-null  object
 3   data_referencia  764508 non-null  object
 4   agente           5832 non-null    object
 5   arma             5832 non-null    object
 6   faixa_etaria     1944 non-null    object
 7   feminino         675614 non-null  float64
 8   masculino        675615 non-null  float64
 9   nao_informado    676032 non-null  float64
 10  total_vitima     684972 non-null  float64
 11  total            76237 non-null   float64
 12  total_peso       1224 non-null    float64
 13  abrangencia      764508 non-null  object
dtypes: float64(6), object(8)
memory usage: 81.7+ MB

In [13]:
df_2023.head()

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,1/1/2023,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,1/2/2023,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,1/3/2023,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,1/4/2023,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,1/5/2023,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [21]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764508 entries, 0 to 764507
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   uf               764508 non-null  object
 1   municipio        764508 non-null  object
 2   evento           764508 non-null  object
 3   data_referencia  764508 non-null  object
 4   agente           5832 non-null    object
 5   arma             5832 non-null    object
 6   faixa_etaria     1944 non-null    object
 7   feminino         677491 non-null  float64
 8   masculino        677873 non-null  float64
 9   nao_informado    677655 non-null  float64
 10  total_vitima     684972 non-null  float64
 11  total            74646 non-null   float64
 12  total_peso       1212 non-null    float64
 13  abrangencia      764508 non-null  object
dtypes: float64(6), object(8)
memory usage: 81.7+ MB

In [14]:
df_2024.head()

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,1/1/2024,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,1/2/2024,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,1/3/2024,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,1/4/2024,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,1/5/2024,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [22]:
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 764700 entries, 0 to 764699
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   uf               764700 non-null  object
 1   municipio        764700 non-null  object
 2   evento           764700 non-null  object
 3   data_referencia  764700 non-null  object
 4   agente           5832 non-null    object
 5   arma             5832 non-null    object
 6   faixa_etaria     1944 non-null    object
 7   feminino         680365 non-null  float64
 8   masculino        680436 non-null  float64
 9   nao_informado    680207 non-null  float64
 10  total_vitima     685164 non-null  float64
 11  total            73905 non-null   float64
 12  total_peso       1207 non-null    float64
 13  abrangencia      764700 non-null  object
dtypes: float64(6), object(8)
memory usage: 81.7+ MB

In [15]:
df_2025.head()

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
0,AC,ACRELÂNDIA,Feminicídio,1/1/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
1,AC,ACRELÂNDIA,Feminicídio,1/2/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
2,AC,ACRELÂNDIA,Feminicídio,1/3/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
3,AC,ACRELÂNDIA,Feminicídio,1/4/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
4,AC,ACRELÂNDIA,Feminicídio,1/5/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual

In [23]:
df_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832071 entries, 0 to 832070
Data columns (total 14 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   uf               832071 non-null  object
 1   municipio        832071 non-null  object
 2   evento           832071 non-null  object
 3   data_referencia  832071 non-null  object
 4   agente           5832 non-null    object
 5   arma             5832 non-null    object
 6   faixa_etaria     1944 non-null    object
 7   feminino         677335 non-null  float64
 8   masculino        677784 non-null  float64
 9   nao_informado    677019 non-null  float64
 10  total_vitima     684987 non-null  float64
 11  total            142075 non-null  float64
 12  total_peso       1190 non-null    float64
 13  abrangencia      832071 non-null  object
dtypes: float64(6), object(8)
memory usage: 88.9+ MB

In [25]:
df_2025.tail()

,uf,municipio,evento,data_referencia,agente,arma,faixa_etaria,feminino,masculino,nao_informado,total_vitima,total,total_peso,abrangencia
832066,TO,XAMBIOÁ,Tentativa de homicídio,1/8/2025,NaN,NaN,NaN,0.0,3.0,0.0,3.0,NaN,NaN,Estadual
832067,TO,XAMBIOÁ,Tentativa de homicídio,1/9/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
832068,TO,XAMBIOÁ,Tentativa de homicídio,1/10/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
832069,TO,XAMBIOÁ,Tentativa de homicídio,1/11/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual
832070,TO,XAMBIOÁ,Tentativa de homicídio,1/12/2025,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,Estadual